### ISSUE TITLE
Getting denied error despite valid PAT when pulling image with Docker pull

### ISSUE THREAD

**Issue by kadiralan** [gsoft-inc/azure-cli-credentials-proxy#6]
**Describe the bug**
I'm getting a denied error even though I created a token with read:packages scope. I can't pull the image.

**To Reproduce**
1 - Create PAT with read:packages scope.
2 - Run docker login using the PAT you created.
3 - Observe if you can log in successfully.
4 - Run docker pull ghcr.io/gsoft-inc/azure-cli-credentials-proxy:latest.
4 - Observe the "denied" error

**Expected behavior**
I should be able to see that the docker pull command works successfully with the pat I created.

**Comment by asimmon** [comment]
Hi @kadiralan , apologies for the delay and the GitHub packages authentication issue. We'll be publishing the image on Docker Hub soon, so no PAT will be needed.

**Comment by asimmon** [comment]
Hi @kadiralan , I just wanted to let you know that we published the image on Docker Hub, so there will no longer be authentication issues: https://hub.docker.com/r/workleap/azure-cli-credentials-proxy

The README is up-to-date with the right image name. Thanks for your interest!
